
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getPrice_b54117587b
ROOST_METHOD_SIG_HASH=getPrice_d2cb73a47d

Scenario 1: Test when the price is set to a positive value

Details:
  TestName: priceReturnsCorrectValueWhenPositive
  Description: This test checks whether the `getPrice()` method returns the correct value when the price is set to a positive double value.
Execution:
  Arrange: Create an instance of the `Product` class and use the `setPrice()` method to assign a positive double value (e.g., 25.99) to the `price` field.
  Act: Call the `getPrice()` method on the `Product` instance.
  Assert: Compare the returned value with the expected value (25.99) using an appropriate JUnit assertion method.
Validation:
  The assertion verifies that `getPrice()` accurately retrieves the stored positive value, ensuring proper functionality for regular scenarios involving positive prices.

*/

// ********RoostGPT********

package com.bootexample4.products.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

public class ProductGetPriceTest {

	@Test
	@Tag("valid")
	public void priceReturnsCorrectValueWhenPositive() {
		// Arrange
		Product product = new Product();
		product.setPrice(25.99);
		// Act
		double actualPrice = product.getPrice();
		// Assert
		assertEquals(25.99, actualPrice, 0.001);
	}

}